server:
  port: 9130
custom:
  jwt-secret: "5jbYUM3b2CicnbQG8VvdeBclxua6mrkGDF10KuKUq1AAi7aZEg4Mmbg14qnChdze"
  
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: my-topic
      
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/NomNomExpress
    username: negiG
    password: negiG@pswd123
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

    generate-ddl: false
    show-sql: false